**CSGo Project**

**Counter-Strike (CS)** is a popular series of tactical first-person shooter (FPS) video games that have been enjoyed by gamers worldwide for many years. The series originated as a modification for the popular game Half-Life and quickly gained its own dedicated following. Here's an overview of Counter-Strike:

**Gameplay Overview:**

Counter-Strike is primarily a multiplayer game where two teams, the Counter-Terrorists (CTs) and the Terrorists (Ts), compete against each other.

The objective of each round varies based on the game mode, but the primary goals include:

**Counter-Terrorists:** Prevent the Terrorists from achieving their objectives, such as defusing a bomb or rescuing hostages.

**Terrorists:** Achieve their objectives, which may include planting a bomb at a designated site or holding hostages.
Rounds are relatively short, typically lasting a few minutes, and players have only one life per round. When a player is eliminated, they must wait until the next round to respawn.

**Key Features:**

**Weapons:** Players can purchase and use a wide variety of firearms, grenades, and equipment. The choice of weaponry is an essential strategic element in the game.

**Economy:** Players earn in-game money based on their performance in the previous rounds. Money is used to buy weapons and equipment for the next round.

**Maps:** Counter-Strike features a range of maps, each with its own layout and objectives. Popular maps include Dust II, Mirage, Inferno, and more.

**Teamwork:** Successful gameplay in Counter-Strike heavily relies on teamwork, communication, and strategy. Players often coordinate their actions with their teammates to achieve objectives.

**Competitive Play:** Counter-Strike is well-known for its competitive scene, with professional esports tournaments held worldwide.

**Popular Game Modes:**

**Bomb Defusal (de_):** In this mode, Terrorists attempt to plant a bomb at one of the designated bomb sites, while Counter-Terrorists aim to prevent the bomb from being planted or defuse it if it's planted.

**Hostage Rescue (cs_):** In hostage rescue mode, Counter-Terrorists must rescue hostages held by the Terrorists, while the Terrorists aim to prevent the rescues.

**Arms Race:** A fast-paced mode where players cycle through a series of weapons, aiming to be the first to get a kill with each weapon.

**Deathmatch:** A mode where players respawn quickly and aim to get as many kills as possible within a set time limit.

**Wingman:** A 2v2 competitive mode with smaller maps and shorter rounds.

Counter-Strike has evolved over the years with different versions, including Counter-Strike 1.6, Counter-Strike: Source, and Counter-Strike: Global Offensive (CS:GO), which is the most recent and widely played installment as of my last knowledge update in September 2021.

CS:GO is known for its competitive gameplay, professional esports scene, and ongoing updates that have kept the game relevant and enjoyable for players worldwide. It remains a cornerstone of the first-person shooter genre.

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [21]:
#Load data set
df = pd.read_csv('csgo.csv')

In [22]:
df.head()

   time_left  ct_score  ...  t_grenade_decoygrenade round_winner
0     175.00       0.0  ...                     0.0           CT
1     156.03       0.0  ...                     0.0           CT
2      96.03       0.0  ...                     0.0           CT
3      76.03       0.0  ...                     0.0           CT
4     174.97       1.0  ...                     0.0           CT

[5 rows x 97 columns]

# EDA

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object
 4   bomb_planted                  122410 non-null  bool
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-null  float64
 13  ct_defuse_kits                122410 non-null  float64
 14  ct_players_alive              122410 non-null  float64
 15  t_players_alive               122410 non-null  float64
 16  ct_weapon_ak47                122410 non-null  float64
 17  t_weapon_ak47                 122410 non-null  float64
 18  ct_weapon_aug                 122410 non-null  float64
 19  t_weapon_aug                  122410 non-null  float64
 20  ct_weapon_awp                 122410 non-null  float64
 21  t_weapon_awp                  122410 non-null  float64
 22  ct_weapon_bizon               122410 non-null  float64
 23  t_weapon_bizon                122410 non-null  float64
 24  ct_weapon_cz75auto            122410 non-null  float64
 25  t_weapon_cz75auto             122410 non-null  float64
 26  ct_weapon_elite               122410 non-null  float64
 27  t_weapon_elite                122410 non-null  float64
 28  ct_weapon_famas               122410 non-null  float64
 29  t_weapon_famas                122410 non-null  float64
 30  ct_weapon_g3sg1               122410 non-null  float64
 31  t_weapon_g3sg1                122410 non-null  float64
 32  ct_weapon_galilar             122410 non-null  float64
 33  t_weapon_galilar              122410 non-null  float64
 34  ct_weapon_glock               122410 non-null  float64
 35  t_weapon_glock                122410 non-null  float64
 36  ct_weapon_m249                122410 non-null  float64
 37  t_weapon_m249                 122410 non-null  float64
 38  ct_weapon_m4a1s               122410 non-null  float64
 39  t_weapon_m4a1s                122410 non-null  float64
 40  ct_weapon_m4a4                122410 non-null  float64
 41  t_weapon_m4a4                 122410 non-null  float64
 42  ct_weapon_mac10               122410 non-null  float64
 43  t_weapon_mac10                122410 non-null  float64
 44  ct_weapon_mag7                122410 non-null  float64
 45  t_weapon_mag7                 122410 non-null  float64
 46  ct_weapon_mp5sd               122410 non-null  float64
 47  t_weapon_mp5sd                122410 non-null  float64
 48  ct_weapon_mp7                 122410 non-null  float64
 49  t_weapon_mp7                  122410 non-null  float64
 50  ct_weapon_mp9                 122410 non-null  float64
 51  t_weapon_mp9                  122410 non-null  float64
 52  ct_weapon_negev               122410 non-null  float64
 53  t_weapon_negev                122410 non-null  float64
 54  ct_weapon_nova                122410 non-null  float64
 55  t_weapon_nova                 122410 non-null  float64
 56  ct_weapon_p90                 122410 non-null  float64
 57  t_weapon_p90                  122410 non-null  float64
 58  ct_weapon_r8revolver          122410 non-null  float64
 59  t_weapon_r8revolver           122410 non-null  float64
 60  ct_weapon_sawedoff            122410 non-null  float64
 61  t_weapon_sawedoff             122410 non-null  float64
 62  ct_weapon_scar20              122410 non-null  float64
 63  t_weapon_scar20               122410 non-null  float64
 64  ct_weapon_sg553               122410 non-null  float64
 65  t_weapon_sg553                122410 non-null  float64
 66  ct_weapon_ssg08               122410 non-null  float64
 67  t_weapon_ssg08                122410 non-null  float64
 68  ct_weapon_ump45               122410 non-null  float64
 69  t_weapon_ump45                122410 non-null  float64
 70  ct_weapon_xm1014              122410 non-null  float64
 71  t_weapon_xm1014               122410 non-null  float64
 72  ct_weapon_deagle              122410 non-null  float64
 73  t_weapon_deagle               122410 non-null  float64
 74  ct_weapon_fiveseven           122410 non-null  float64
 75  t_weapon_fiveseven            122410 non-null  float64
 76  ct_weapon_usps                122410 non-null  float64
 77  t_weapon_usps                 122410 non-null  float64
 78  ct_weapon_p250                122410 non-null  float64
 79  t_weapon_p250                 122410 non-null  float64
 80  ct_weapon_p2000               122410 non-null  float64
 81  t_weapon_p2000                122410 non-null  float64
 82  ct_weapon_tec9                122410 non-null  float64
 83  t_weapon_tec9                 122410 non-null  float64
 84  ct_grenade_hegrenade          122410 non-null  float64
 85  t_grenade_hegrenade           122410 non-null  float64
 86  ct_grenade_flashbang          122410 non-null  float64
 87  t_grenade_flashbang           122410 non-null  float64
 88  ct_grenade_smokegrenade       122410 non-null  float64
 89  t_grenade_smokegrenade        122410 non-null  float64
 90  ct_grenade_incendiarygrenade  122410 non-null  float64
 91  t_grenade_incendiarygrenade   122410 non-null  float64
 92  ct_grenade_molotovgrenade     122410 non-null  float64
 93  t_grenade_molotovgrenade      122410 non-null  float64
 94  ct_grenade_decoygrenade       122410 non-null  float64
 95  t_grenade_decoygrenade        122410 non-null  float64
 96  round_winner                  122410 non-null  object
dtypes: bool(1), float64(94), object(2)
memory usage: 89.8+ MB

In [24]:
df.shape

(122410, 97)

In [25]:
# Null check
df.isnull().sum().sum()

0

In [26]:
# Duplicate check
df.duplicated().sum()

4962

In [27]:
# Out of 4,22,410 we have 4,962 as duplicate data, so we can drop them
df.drop_duplicates(inplace=True)

In [28]:
df.duplicated().sum()

0

# Data Preprocessing

Types of Label encoding
1) Label Encoding - ( Depending on Alphabetical order )

Apple =  0
Orange = 3
Banana = 1
Cherry = 2

2) Ordinal Encoding - ( Depending on order of values)   , od = ordinalEncoder([low,medium,high,highest])

High    = 2
Medium  = 1
Low     = 0
Highest = 3

3) One Hot Encoding - ( It will create seperate seperate colunmns for all encoded values)

Maritial status        Single       Married      Relationship
1) Single                1            0              0
2) Married               0            1              0
3) Relationship          0            0              1

In [29]:
# Label Encoding to convert "map" ,"bomb_planted	" column containin categorical values to numerical values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['bomb_planted'] = le.fit_transform(df['bomb_planted'])
df['map'] = le.fit_transform(df['map'])

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 117448 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   time_left                     117448 non-null  float64
 1   ct_score                      117448 non-null  float64
 2   t_score                       117448 non-null  float64
 3   map                           117448 non-null  int32
 4   bomb_planted                  117448 non-null  int64
 5   ct_health                     117448 non-null  float64
 6   t_health                      117448 non-null  float64
 7   ct_armor                      117448 non-null  float64
 8   t_armor                       117448 non-null  float64
 9   ct_money                      117448 non-null  float64
 10  t_money                       117448 non-null  float64
 11  ct_helmets                    117448 non-null  float64
 12  t_helmets                     117448 non-null  float64
 13  ct_defuse_kits                117448 non-null  float64
 14  ct_players_alive              117448 non-null  float64
 15  t_players_alive               117448 non-null  float64
 16  ct_weapon_ak47                117448 non-null  float64
 17  t_weapon_ak47                 117448 non-null  float64
 18  ct_weapon_aug                 117448 non-null  float64
 19  t_weapon_aug                  117448 non-null  float64
 20  ct_weapon_awp                 117448 non-null  float64
 21  t_weapon_awp                  117448 non-null  float64
 22  ct_weapon_bizon               117448 non-null  float64
 23  t_weapon_bizon                117448 non-null  float64
 24  ct_weapon_cz75auto            117448 non-null  float64
 25  t_weapon_cz75auto             117448 non-null  float64
 26  ct_weapon_elite               117448 non-null  float64
 27  t_weapon_elite                117448 non-null  float64
 28  ct_weapon_famas               117448 non-null  float64
 29  t_weapon_famas                117448 non-null  float64
 30  ct_weapon_g3sg1               117448 non-null  float64
 31  t_weapon_g3sg1                117448 non-null  float64
 32  ct_weapon_galilar             117448 non-null  float64
 33  t_weapon_galilar              117448 non-null  float64
 34  ct_weapon_glock               117448 non-null  float64
 35  t_weapon_glock                117448 non-null  float64
 36  ct_weapon_m249                117448 non-null  float64
 37  t_weapon_m249                 117448 non-null  float64
 38  ct_weapon_m4a1s               117448 non-null  float64
 39  t_weapon_m4a1s                117448 non-null  float64
 40  ct_weapon_m4a4                117448 non-null  float64
 41  t_weapon_m4a4                 117448 non-null  float64
 42  ct_weapon_mac10               117448 non-null  float64
 43  t_weapon_mac10                117448 non-null  float64
 44  ct_weapon_mag7                117448 non-null  float64
 45  t_weapon_mag7                 117448 non-null  float64
 46  ct_weapon_mp5sd               117448 non-null  float64
 47  t_weapon_mp5sd                117448 non-null  float64
 48  ct_weapon_mp7                 117448 non-null  float64
 49  t_weapon_mp7                  117448 non-null  float64
 50  ct_weapon_mp9                 117448 non-null  float64
 51  t_weapon_mp9                  117448 non-null  float64
 52  ct_weapon_negev               117448 non-null  float64
 53  t_weapon_negev                117448 non-null  float64
 54  ct_weapon_nova                117448 non-null  float64
 55  t_weapon_nova                 117448 non-null  float64
 56  ct_weapon_p90                 117448 non-null  float64
 57  t_weapon_p90                  117448 non-null  float64
 58  ct_weapon_r8revolver          117448 non-null  float64
 59  t_weapon_r8revolver           117448 non-null  float64
 60  ct_weapon_sawedoff            117448 non-null  float64
 61  t_weapon_sawedoff             117448 non-null  float64
 62  ct_weapon_scar20              117448 non-null  float64
 63  t_weapon_scar20               117448 non-null  float64
 64  ct_weapon_sg553               117448 non-null  float64
 65  t_weapon_sg553                117448 non-null  float64
 66  ct_weapon_ssg08               117448 non-null  float64
 67  t_weapon_ssg08                117448 non-null  float64
 68  ct_weapon_ump45               117448 non-null  float64
 69  t_weapon_ump45                117448 non-null  float64
 70  ct_weapon_xm1014              117448 non-null  float64
 71  t_weapon_xm1014               117448 non-null  float64
 72  ct_weapon_deagle              117448 non-null  float64
 73  t_weapon_deagle               117448 non-null  float64
 74  ct_weapon_fiveseven           117448 non-null  float64
 75  t_weapon_fiveseven            117448 non-null  float64
 76  ct_weapon_usps                117448 non-null  float64
 77  t_weapon_usps                 117448 non-null  float64
 78  ct_weapon_p250                117448 non-null  float64
 79  t_weapon_p250                 117448 non-null  float64
 80  ct_weapon_p2000               117448 non-null  float64
 81  t_weapon_p2000                117448 non-null  float64
 82  ct_weapon_tec9                117448 non-null  float64
 83  t_weapon_tec9                 117448 non-null  float64
 84  ct_grenade_hegrenade          117448 non-null  float64
 85  t_grenade_hegrenade           117448 non-null  float64
 86  ct_grenade_flashbang          117448 non-null  float64
 87  t_grenade_flashbang           117448 non-null  float64
 88  ct_grenade_smokegrenade       117448 non-null  float64
 89  t_grenade_smokegrenade        117448 non-null  float64
 90  ct_grenade_incendiarygrenade  117448 non-null  float64
 91  t_grenade_incendiarygrenade   117448 non-null  float64
 92  ct_grenade_molotovgrenade     117448 non-null  float64
 93  t_grenade_molotovgrenade      117448 non-null  float64
 94  ct_grenade_decoygrenade       117448 non-null  float64
 95  t_grenade_decoygrenade        117448 non-null  float64
 96  round_winner                  117448 non-null  object
dtypes: float64(94), int32(1), int64(1), object(1)
memory usage: 87.4+ MB

In [31]:
df

        time_left  ct_score  ...  t_grenade_decoygrenade  round_winner
0          175.00       0.0  ...                     0.0            CT
1          156.03       0.0  ...                     0.0            CT
2           96.03       0.0  ...                     0.0            CT
3           76.03       0.0  ...                     0.0            CT
4          174.97       1.0  ...                     0.0            CT
...           ...       ...  ...                     ...           ...
122405      15.41      11.0  ...                     0.0             T
122406     174.93      11.0  ...                     0.0             T
122407     114.93      11.0  ...                     0.0             T
122408      94.93      11.0  ...                     0.0             T
122409      74.93      11.0  ...                     0.0             T

[117448 rows x 97 columns]

# Build Machine Leaning Models of classification type by using all 97 columns

In [36]:
x=df.iloc[:,:-1] 
y=df["round_winner"]

In [37]:
#train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=34)

In [38]:
#Building logistic regression model
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(x_train , y_train)
y_pred = model1.predict(x_test)

c:\Users\sahaj\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [39]:
from sklearn.metrics import * 
print("Accuracy score of Logistic regression model by using all 96 columns : ", accuracy_score(y_test , y_pred)*100)

Accuracy score of Logistic regression model by using all 96 columns :  74.25287356321839

In [40]:
#Building Decision tree
from sklearn.tree import DecisionTreeClassifier
model2 = DecisionTreeClassifier()
model2.fit(x_train, y_train)
y_pred = model2.predict(x_test)

In [41]:
from sklearn.metrics import *  
print("Accuracy score of Decision Tree model by using all 96 columns : ", accuracy_score(y_test , y_pred)*100)

Accuracy score of Decision Tree model by using all 96 columns :  81.02596849723287

In [42]:
# Building Random forest
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier()
model3.fit(x_train, y_train)
y_pred = model3.predict(x_test)

In [43]:
from sklearn.metrics import *  
print("Accuracy score of Random Forest model by using all 96 columns : ", accuracy_score(y_test , y_pred)*100)

Accuracy score of Random Forest model by using all 96 columns :  86.79012345679013

**Apply Hyper paramter tuning on this random forest model, as we are getting highest accuracy using random forest**

In [46]:
from sklearn.model_selection import GridSearchCV

param_grid = {'n_estimators':[100,200,300],
              'max_depth':[5,10,15,20],
              'min_samples_split':[2,5,10],
              'min_samples_leaf':[1,2,4],
              'criterion':['gini','entropy']}

model4 = RandomForestClassifier(random_state= 3)
grid_search = GridSearchCV(estimator = model4, param_grid=param_grid , cv=3)

In [47]:
grid_search.fit(x_train, y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=3),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 10, 15, 20],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]})

In [48]:
y_pred = grid_search.predict(x_test)

In [49]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=20, n_estimators=300, random_state=3)

In [50]:
print("Accuracy score of Random Forest model by using all 96 columns : ", accuracy_score(y_test , y_pred)*100)

Accuracy score of Random Forest model by using all 96 columns :  84.02298850574714

### As maximum accuracy we got is 86.6% so now we will apply Dimensionality reduction technique to increase the performance of models by reducing the no of columns and then selecting only the important columns

In [51]:
# Feature Selection Techniques

# VIF - Variance Inflation Factor
# RFE - Recursive Feature Elimination
# LDA - Linear Discriminant Analysis

# Feature Extraction Techniques

# PCA - Principal Componenet Analysis
# LDA - Linear Discriminant Analysis

# Building model with LDA

**Let's proceed with LDA for feature selection but not extraction as we are having only 2 classes in the target variables**

LDA tries to reduce the number of features by picking the ones that are most useful for distinguishing between the groups.

For example, if you have 10 features, LDA might tell you that only 3 of them are really good at separating the groups.

**Standardize the data**

**LDA is sensitive to feature scales**: LDA relies on maximizing the separation between classes by finding the directions where classes are most distinguishable.

If one feature has a much larger range (e.g., salary in thousands vs. age in years), it can dominate the model and distort the results.

**Scaling the features ensures that all features contribute equally to the analysis by bringing them onto the same scale.**

In [62]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

x_train = sc.fit_transform(x_train)  # .fit_transform to apply strandard scaler on Training data
x_test = sc.transform(x_test)        # .transform to apply strandard scaler on Test data       # .transform to apply strandard scaler on Test data

In [63]:
# Apply LDa on this new transformed data
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()

lda.fit(x_train , y_train)
lda.transform(x_test)

array([[-0.81926606],
       [-0.20646063],
       [-1.2027105 ],
       ...,
       [-3.11199387],
       [-0.58398431],
       [ 3.15241551]])

**lda.coef_:** This retrieves the coefficients (or weights) of the features from the trained Linear Discriminant Analysis (LDA) model. These coefficients indicate the importance of each feature in distinguishing between classes.

**np.abs(lda.coef_):** The absolute value of the coefficients is taken. This removes any negative signs, focusing on the magnitude of the feature importance rather than its direction (positive or negative influence).

**np.exp(...):** The exponential function (e^x, where e is Euler's number, approximately 2.718) is applied to each of these absolute values. This operation transforms the coefficients by exponentially scaling them.

In [64]:
lda.coef_  # Now some values are negative some are positive

array([[ 1.40798218e-01, -1.63779539e-02,  1.65392901e-02,
        -8.44119919e-02,  2.45841039e-01, -4.25778801e-01,
         3.25206002e-01, -6.05044865e-01,  6.42755761e-01,
        -2.14088433e-01,  1.63286872e-01,  4.99608671e-02,
         7.13517526e-02, -3.50006793e-02, -2.23093635e-01,
         3.81277147e-01, -1.92314735e-01,  6.25316797e-01,
        -2.12493284e-01,  3.78495199e-02, -3.11983894e-01,
         2.44962696e-01,  1.06644140e-15, -1.56787590e-03,
         1.38840808e-02,  2.70750360e-04, -8.16982190e-03,
         1.45702604e-02, -1.41816668e-01,  4.89809549e-02,
        -4.85788654e-16,  2.09674722e-02, -5.31379540e-02,
         1.37751078e-01,  1.92835708e-02, -1.71303471e-01,
         1.14972095e-02, -9.67866168e-17, -9.06436363e-02,
         4.98581963e-02, -4.67518881e-01,  1.13211531e-01,
        -1.40641808e-02,  1.08913917e-01, -1.83591480e-02,
         4.22382388e-03, -1.03658699e-02,  3.68348304e-02,
         7.66327721e-03, -1.10885542e-02, -1.13307614e-01,
         3.97381250e-02, -1.46960398e-17, -3.71205135e-17,
        -1.27126380e-02, -2.51179351e-02, -2.58388323e-02,
         1.70787449e-02,  6.95971292e-17, -6.42861996e-03,
         1.37514124e-17,  1.43328160e-02,  8.33175815e-03,
         8.91586098e-17, -2.08865481e-01,  5.68169961e-01,
        -8.25881264e-02,  1.81067895e-02, -4.30754793e-02,
         9.39543415e-02, -2.03907205e-02,  2.32238959e-03,
         2.69303940e-02, -1.49312297e-02,  3.37016610e-02,
        -3.69002175e-02,  1.24240245e-01,  3.58209412e-02,
         5.63204531e-02, -1.94758378e-02,  5.69087054e-02,
         7.31847564e-03, -4.46916184e-03,  1.96270505e-03,
        -9.92870062e-03, -2.55954486e-03,  1.71511066e-02,
        -1.92516460e-01,  8.11853597e-02, -2.30364069e-01,
         9.48200884e-02, -1.43216491e-02,  1.10580825e-02,
        -1.07292562e-01, -1.34194642e-04,  1.82069910e-02]])

In [55]:
correct_lda_coeff = np.exp(np.abs(lda.coef_))
correct_lda_coeff = correct_lda_coeff.flatten()  # to convert 2d to 1d
correct_lda_coeff  # This have importance of all 96 columns

array([ 1.00265011,  1.00341021,  1.00341902,  1.04464809,  2.14843661,
        1.00318545,  1.00230033,  1.00356466,  1.00369962,  1.00001891,
        1.00001334,  1.02766802,  1.03674689,  1.02192055,  1.20045996,
        1.35788136,  1.38626207,  1.57997756,  1.57515355,  1.50742647,
        1.58672359,  1.6644145 ,  1.        ,  1.18521354,  1.03125505,
        1.00069882,  1.13893959,  1.41038129,  1.43343759,  2.00629996,
        1.        ,  1.7055158 ,  1.59184537,  1.39554341,  1.23965968,
        1.11052858, 33.92692153,  1.        ,  1.40465691,  2.47972298,
        1.46480224,  1.56541943,  1.15688279,  1.29815701,  1.30229961,
        1.91050776,  1.31214368,  1.93798985,  1.17991449,  1.26256479,
        1.2678065 ,  1.60222643,  1.        ,  1.        ,  1.50149809,
       18.35987214,  6.82860536,  3.8643683 ,  1.        ,  2.10606398,
        1.        ,  3.38240727,  1.35133791,  1.        ,  1.45069671,
        1.64160632,  1.35604656,  1.13024926,  1.20064034,  1.55132439,
        1.25389183,  1.14685055,  1.03240938,  1.01817704,  1.12194408,
        1.43598881,  1.0813778 ,  1.08378302,  1.10953826,  1.03416468,
        1.14454913,  1.0997728 ,  1.04831791,  1.01013639,  1.00774747,
        1.00314803,  1.0097501 ,  1.11265416,  1.04783902,  1.13374747,
        1.06707461,  1.10230861,  1.04909366,  1.06631478,  1.00078932,
        1.11945369])

In [66]:
features_names = x.columns
features_names

Index(['time_left', 'ct_score', 't_score', 'map', 'bomb_planted', 'ct_health',
       't_health', 'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets',
       't_helmets', 'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev', 'ct_weapon_nova', 't_weapon_nova',
       'ct_weapon_p90', 't_weapon_p90', 'ct_weapon_r8revolver',
       't_weapon_r8revolver', 'ct_weapon_sawedoff', 't_weapon_sawedoff',
       'ct_weapon_scar20', 't_weapon_scar20', 'ct_weapon_sg553',
       't_weapon_sg553', 'ct_weapon_ssg08', 't_weapon_ssg08',
       'ct_weapon_ump45', 't_weapon_ump45', 'ct_weapon_xm1014',
       't_weapon_xm1014', 'ct_weapon_deagle', 't_weapon_deagle',
       'ct_weapon_fiveseven', 't_weapon_fiveseven', 'ct_weapon_usps',
       't_weapon_usps', 'ct_weapon_p250', 't_weapon_p250', 'ct_weapon_p2000',
       't_weapon_p2000', 'ct_weapon_tec9', 't_weapon_tec9',
       'ct_grenade_hegrenade', 't_grenade_hegrenade', 'ct_grenade_flashbang',
       't_grenade_flashbang', 'ct_grenade_smokegrenade',
       't_grenade_smokegrenade', 'ct_grenade_incendiarygrenade',
       't_grenade_incendiarygrenade', 'ct_grenade_molotovgrenade',
       't_grenade_molotovgrenade', 'ct_grenade_decoygrenade',
       't_grenade_decoygrenade'],
      dtype='object')

In [67]:
# Now lets map both column name and column importance together

df_feature_score = pd.DataFrame({"Columns names" :features_names , "Column Importance":correct_lda_coeff})
df_feature_score

                  Columns names  Column Importance
0                     time_left           1.151192
1                      ct_score           1.016513
2                       t_score           1.016677
3                           map           1.088077
4                  bomb_planted           1.278696
..                          ...                ...
91  t_grenade_incendiarygrenade           1.014425
92    ct_grenade_molotovgrenade           1.011119
93     t_grenade_molotovgrenade           1.113260
94      ct_grenade_decoygrenade           1.000134
95       t_grenade_decoygrenade           1.018374

[96 rows x 2 columns]

In [68]:
# Lets use top 50 columns by arranging them

top_50_columns = df_feature_score.nlargest(50 , "Column Importance")
top_50_columns

                   Columns names  Column Importance
8                        t_armor           1.901714
17                 t_weapon_ak47           1.868838
7                       ct_armor           1.831334
65                t_weapon_sg553           1.765034
40                ct_weapon_m4a4           1.596029
5                      ct_health           1.530782
15               t_players_alive           1.464153
6                       t_health           1.384316
20                 ct_weapon_awp           1.366133
4                   bomb_planted           1.278696
21                  t_weapon_awp           1.277574
89        t_grenade_smokegrenade           1.259058
14              ct_players_alive           1.249938
9                       ct_money           1.238732
18                 ct_weapon_aug           1.236758
64               ct_weapon_sg553           1.232279
87           t_grenade_flashbang           1.212296
16                ct_weapon_ak47           1.212052
35                t_weapon_glock           1.186851
10                       t_money           1.177374
28               ct_weapon_famas           1.152365
0                      time_left           1.151192
33              t_weapon_galilar           1.147690
76                ct_weapon_usps           1.132288
50                 ct_weapon_mp9           1.119976
41                 t_weapon_m4a4           1.119869
43                t_weapon_mac10           1.115066
93      t_grenade_molotovgrenade           1.113260
90  ct_grenade_incendiarygrenade           1.099461
69                t_weapon_ump45           1.098510
38               ct_weapon_m4a1s           1.094879
3                            map           1.088077
66               ct_weapon_ssg08           1.086094
88       ct_grenade_smokegrenade           1.084572
12                     t_helmets           1.073959
80               ct_weapon_p2000           1.058559
78                ct_weapon_p250           1.057937
32             ct_weapon_galilar           1.054575
11                    ct_helmets           1.051230
39                t_weapon_m4a1s           1.051122
29                t_weapon_famas           1.050200
68               ct_weapon_ump45           1.044017
51                  t_weapon_mp9           1.040538
19                  t_weapon_aug           1.038575
75            t_weapon_fiveseven           1.037589
47                t_weapon_mp5sd           1.037522
77                 t_weapon_usps           1.036470
13                ct_defuse_kits           1.035620
74           ct_weapon_fiveseven           1.034276
72              ct_weapon_deagle           1.027296

In [69]:
# Lets have index of these top 50 columns so we can store then in x and then split the data
top_50_columns_index = top_50_columns.index
top_50_columns_index

Index([ 8, 17,  7, 65, 40,  5, 15,  6, 20,  4, 21, 89, 14,  9, 18, 64, 87, 16,
       35, 10, 28,  0, 33, 76, 50, 41, 43, 93, 90, 69, 38,  3, 66, 88, 12, 80,
       78, 32, 11, 39, 29, 68, 51, 19, 75, 47, 77, 13, 74, 72],
      dtype='int64')

In [70]:
# New x_train with top 50 important columns
x_train = x_train[: , top_50_columns_index]

In [71]:
# New x_test with top 50 important columns
x_test = x_test[: , top_50_columns_index]

In [72]:
# Build a logistic regression model by using new data
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()
model1.fit(x_train , y_train)
y_pred = model1.predict(x_test)
print("Accuracy score of Logistic Regression model by using top 50 columns given by LDA is", accuracy_score(y_test , y_pred)*100)

Accuracy score of Logistic Regression model by using top 50 columns given by LDA is 75.32567049808429

In [73]:

# Decision Tree Model
from sklearn.tree import DecisionTreeClassifier
model2=DecisionTreeClassifier()
model2.fit(x_train , y_train)
y_pred = model2.predict(x_test)
print("Accuracy score of Decision Tree model by using top 50 columns given by LDA is : ", accuracy_score(y_test , y_pred)*100)

Accuracy score of Decision Tree model by using top 50 columns given by LDA is :  80.49808429118774

In [ ]:
# Random Forest Model
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier()
model3.fit(x_train , y_train)
y_pred = model3.predict(x_test)
from sklearn.metrics import *    # import * means import all things at once like accuracy_score , rmse_score , r2_score
print("Accuracy score of Random Forest model by using top 50 columns given by LDA is: ", accuracy_score(y_test , y_pred)*100)